import React from 'react';
import {
  Flower2,
  Leaf,
  Heart,
  Coffee,
  Tent,
  Car,
  UtensilsCrossed,
  Cake,
  Gift,
  Sparkles,
  Camera,
  Mail,
  Lock,
  Key,
  Music,
  Flame,
  Star,
  Send,
  Bookmark,
  Clover,
  Disc,
  Smile,
  Feather,
  Sun,
  Tag,
  Cat,
  Mic,
  Guitar,
} from 'lucide-react';

const iconMap = {
  flower: Flower2,
  leaf: Leaf,
  heart: Heart,
  coffee: Coffee,
  tent: Tent,
  car: Car,
  pizza: UtensilsCrossed,
  cake: Cake,
  gift: Gift,
  sparkles: Sparkles,
  camera: Camera,
  mail: Mail,
  lock: Lock,
  key: Key,
  music: Music,
  flame: Flame,
  star: Star,
  send: Send,
  plane: Send,
  bookmark: Bookmark,
  clover: Clover,
  disc: Disc,
  smile: Smile,
  feather: Feather,
  sun: Sun,
  tag: Tag,
  cat: Cat,
  mic: Mic,
  guitar: Guitar,
  plushie: Sparkles,
};

export default function IconRenderer({ name, className = "w-5 h-5", fallback = "sparkles" }) {
  const IconComponent = iconMap[name?.toLowerCase()] || iconMap[fallback] || Sparkles;
  return <IconComponent className={className} />;
}
